apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-jira-tracker-mcp
  labels:
    app: customer-jira-tracker-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-jira-tracker-mcp
  template:
    metadata:
      labels:
        app: customer-jira-tracker-mcp
    spec:
      containers:
      - name: customer-jira-tracker-mcp
        image: customer-jira-tracker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: CUSTOMER_JIRA_STORAGE
          value: "/data"
        - name: PORT
          value: "8080"
        - name: REQUIRE_AUTH
          value: "true"
        - name: CUSTOMER_JIRA_TRACKER_API_KEY
          valueFrom:
            secretKeyRef:
              name: customer-jira-tracker-secret
              key: api-key
        volumeMounts:
        - name: data-storage
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: customer-jira-tracker-data
