apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-jira-tracker-data
  labels:
    app: customer-jira-tracker-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: gp2  # Uncomment and set to your desired storage class if needed
